export default {
  // 创建订单
  orderInfo: {
    items: [],
    tasks: [],
    type: 0,
    remark: '',
    sourceType: 9,
    priceSupply: '', // 小单费
    pricePay: '',
    receiverName: '',
    receiverAddress: '',
    receiverMobile: '',
    province: '', // 省市区名称及代码
    provinceId: '',
    city: '',
    cityId: '',
    area: '',
    areaId: '',
    addressId: '',
    isCustomer: 0, // 是否查到客户信息,
    customerName: '',
    spuId: '',
    categoryId: '',
    priceSupplyType: 0,
    userId: null,
    saleOrderNo: '',
    passMobile: '',
    reserveMobile: '',
    homeDeviceId: 0,
    settlementType: null,
    payType: 1,
    paymentWay: 1,
    orderEnvironmentPicture: '',
    commonCommodityNames: ''
  },
  brandList: {
    name: '',
    display: 1,
    pageIndex: 1,
    pageSize: 10
  },
  spuList: {
    brandId: '',
    brandName: '',
    buyType: '',
    categoryId1: '',
    categoryId2: '',
    categoryId3: '',
    code: '',
    content: '',
    createTime: '',
    createUserId: '',
    id: 0,
    images: '',
    merchantCode: '',
    merchantName: '',
    name: '',
    pageIndex: 1,
    pageSize: 10,
    productInfo: '',
    queryType: 2,
    saleType: '',
    shareName: '',
    source: '',
    type: '',
    updateTime: '',
    updateUserId: '',
    valid: '',
    wxaCode: '',
    startTime: '',
    endTime: '',
  },
  spuUpdate: {
    id: null,
    name: null,
    shareName: null,
    saleType: null,
    productInfo: '',
    detail: {
      description: '',
      afterService: '',
      id: null,
      packingList: '',
      spuId: null
    },
    brandId: null,
    brandName: null,
    categoryId3: null,
    attributes: null,
    merchantCode: null,
    merchantName: null,
    skus: null,
    images: null,
    content: '',
    specificationTable: null,
    source: null,
    type: null,
    code: null
  },
  productList: {
    categoryId: '',
    have: true,
    pageNum: 1,
    pageSize: 10,
    spuName: '',
    brandName: '',
    _merchantId: ''
  }
}